### ISSUE TITLE
TypeError for Orientation in BRepClass_FaceExplorer.CurrentEdge

### ISSUE THREAD

**Issue by raovgarimella** [tpaviot/pythonocc-core#1038]
I have a weird TypeError for orientation when I try to use the CurrentEdge method in the BRepClass_FaceExplorer.
This is what I am doing

```python
from OCC.Core.BRepClass import BRepClass_FaceExplorer
from OCC.Core.BRepClass import BRepClass_Edge
from OCC.Core.TopAbs import TopAbs_Orientation

facetopo = BRepClass_FaceExplorer(face)

facetopo.InitWires()  # get ready to explore wires/loops of this face
while (facetopo.MoreWires()):
#    loop = facetopo.CurrentWire()  # SOMEHOW THIS IS MISSING

  edge = BRepClass_Edge()
  edir = TopAbs_Orientation(TopAbs_Orientation.TopAbs_FORWARD)

  print('Type of edge =',type(edge))

  facetopo.InitEdges()
  while (facetopo.MoreEdges()):
    print('Type of edir =',type(edir))
    facetopo.CurrentEdge(edge, edir)  # <------------- I GET A TypeError FOR edir 
    facetopo.NextEdge()

  facetopo.NextWire()
```

But I get the message 
```
Type of edir =  <enum 'TopAbs_Orientation'>
Traceback (most recent call last):
  File "test.py", line 117, in <module>
    facetopo.CurrentEdge(edge, edir)
  File "/home/rao/anaconda3/envs/pyoccenv/lib/python3.7/site-packages/OCC/Core/BRepClass.py", line 531, in CurrentEdge
    return _BRepClass.BRepClass_FaceExplorer_CurrentEdge(self, *args)
TypeError: in method 'BRepClass_FaceExplorer_CurrentEdge', argument 3 of type 'TopAbs_Orientation &'
```

What am I doing wrong?

**Comment by tpaviot** [comment]
Issue confirmed. The TopAbs_Orientation should be returned, but the c++ base library expects a parameter passed by reference, which is not pythonic. The wrapper requires an update.

**Comment by raovgarimella** [comment]
Thanks
