### ISSUE TITLE
error when trying to create display

### ISSUE THREAD

**Issue by garethByers** [tpaviot/pythonocc-core#1087]
This is the error I get when trying to create a display:

Traceback (most recent call last):
  File "I:\IFCopenshell\main.py", line 14, in <module>
    occ_display = ifcopenshell.geom.utils.initialize_display()
  File "E:\conda\envs\pythonOCC\lib\site-packages\ifcopenshell\geom\occ_utils.py", line 97, in initialize_display
    setup()
  File "E:\conda\envs\pythonOCC\lib\site-packages\ifcopenshell\geom\occ_utils.py", line 93, in setup
    light = V3d.V3d_DirectionalLight(viewer_handle)
  File "E:\conda\envs\pythonOCC\lib\site-packages\OCC\Core\V3d.py", line 5271, in __init__
    _V3d.V3d_DirectionalLight_swiginit(self, _V3d.new_V3d_DirectionalLight(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_V3d_DirectionalLight'.
  Possible C/C++ prototypes are:
    V3d_DirectionalLight::V3d_DirectionalLight(V3d_TypeOfOrientation const,Quantity_Color const &,Standard_Boolean const)
    V3d_DirectionalLight::V3d_DirectionalLight(gp_Dir const &,Quantity_Color const &,Standard_Boolean const)

**Comment by cafhach** [comment]
Can you post the content of `main.py`?
