### ISSUE TITLE
Error code: -1073281622 raised from method Init of class Display3d

### ISSUE THREAD

**Issue by ManhoKANG** [tpaviot/pythonocc-core#1172]
My environment is windows 11 Pro, pythonocc 7.7.0 and pyside2 using anaconda.
test.py is as the below:
from OCC.Display.SimpleGui import init_display
from OCC.Core.BRepPrimAPI import BRepPrimAPI_MakeBox

display, start_display, add_menu, add_function_to_menu = init_display()
my_box = BRepPrimAPI_MakeBox(10., 20., 30.).Shape()

display.DisplayShape(my_box, update=True)
start_display()
the messages are as the below:
(pyoccenv) C:\myProject\Gaon\sampleProj>python test.py   
qt-pyside2 backend - Qt version 5.15.6
####### 3D rendering pipe initialisation #####
Display3d class initialization starting ...
Aspect_DisplayConnection created.
OpenGl_GraphicDriver created.
V3d_Viewer created.
AIS_InteractiveContext created.
V3d_View created
WNT window created.
Display3d class successfully initialized.
#########################################
OpenGl information:
  GLvendor: Intel
  GLdevice: Intel(R) UHD Graphics
  GLversion: 4.6.0 - Build 27.20.100.9664
  GLSLversion: 4.60 - Build 27.20.100.9664
  Max texture size: 16384
  Max FBO dump size: 4096x16384
  Max combined texture units: 192
  Max MSAA samples: 16
  Viewport: 1023x767
  Window buffer: RGB8 ALPHA8 DEPTH24 STENCIL8
  ResolutionRatio: 1
  FBO buffer: GL_SRGB8_ALPHA8 GL_DEPTH24_STENCIL8
WNT window created.
Traceback (most recent call last):
  File "C:\myProject\Gaon\sampleProj\test.py", line 4, in <module>
    display, start_display, add_menu, add_function_to_menu = init_display()
  File "C:\Users\mhkang\anaconda3\envs\pyoccenv\lib\site-packages\OCC\Display\SimpleGui.py", line 211, in init_display
    win.canva.InitDriver()
nit(self, handle)
RuntimeError: Aspect_GraphicDeviceDefinitionErrorOpenGl_Window::CreateWindow: wglCreateContext failed. Error code: -1073281622 raised from method Init of class Display3d

**Comment by ManhoKANG** [comment]
My problem was due to graphic card. I have two graphic cards. The error was happened in the below graphic card.
    OpenGl information:
      GLvendor: Intel
      GLdevice: Intel(R) UHD Graphics
      GLversion: 4.6.0 - Build 27.20.100.9664
      GLSLversion: 4.60 - Build 27.20.100.9664

I disabled the upper graphic card and set able the below card.
    OpenGl information:
      GLvendor: NVIDIA Corporation
      GLdevice: NVIDIA GeForce RTX 2070 Super/PCIe/SSE2
      GLversion: 4.6.0 NVIDIA 512.98
      GLSLversion: 4.60 NVIDIA

It work well.
