### ISSUE TITLE
When I add QMenuBar,OCC can't load lib.

### ISSUE THREAD

**Issue by ovo-Tim** [tpaviot/pythonocc-core#1214]
This is my code:
``` python
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from OCC.Core.BRepPrimAPI import BRepPrimAPI_MakeBox
from OCC.Display.OCCViewer import rgb_color
from OCC.Display import OCCViewer

from OCC.Display.backend import load_backend,get_loaded_backend
load_backend("qt-pyside6")
import OCC.Display.qtDisplay as qtDisplay
import sys,os

class MainWindow(QMainWindow):
    BORDER_WIDTH = 5
    def __init__(self):
        super().__init__()

        # self.setWindowFlags(Qt.CustomizeWindowHint)

        self.setGeometry(35, 35, 500, 500)

        self.menu = QMenuBar()
        self.setMenuBar(self.menu)

        self.main_widget = QTabWidget()
        self.setCentralWidget(self.main_widget)

        self.canvas = qtDisplay.qtViewer3d()
        self.canvas.InitDriver()
        self.main_widget.addTab(self.canvas, 'test1')

        self.canvas2 = qtDisplay.qtViewer3d()
        self.canvas2.InitDriver()
        my_box = BRepPrimAPI_MakeBox (10,10,10).Shape()
        self.canvas._display.DisplayShape(my_box,update=True,color=rgb_color(0,1,0))
        self.main_widget.addTab(self.canvas2, 'test2')
        self.main_widget.currentChanged.connect(self.r)
    def r(self):
        self.canvas.InitDriver()
        self.canvas2.InitDriver()

app = QApplication(sys.argv)
win = MainWindow()
win.show()
# win.raise_() 
app.exec_()
```
Errcode:
```
####### 3D rendering pipe initialisation #####
Display3d class initialization starting ...
Aspect_DisplayConnection created.
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
OpenGl_GraphicDriver created.
V3d_Viewer created.
AIS_InteractiveContext created.
V3d_View created
Xw_Window created.
Traceback (most recent call last):
  File "/home/tim/桌面/test.py", line 49, in <module>
    win = MainWindow()
  File "/home/tim/桌面/test.py", line 35, in __init__
    self.canvas.InitDriver()
  File "/home/tim/mambaforge/envs/pythonocc/lib/python3.10/site-packages/OCC/Display/qtDisplay.py", line 104, in InitDriver
    self._display.Create(window_handle=int(self.winId()), parent=self)
  File "/home/tim/mambaforge/envs/pythonocc/lib/python3.10/site-packages/OCC/Display/OCCViewer.py", line 220, in Create
    self.Init(self._window_handle)
  File "/home/tim/mambaforge/envs/pythonocc/lib/python3.10/site-packages/OCC/Core/Visualization.py", line 171, in Init
    return _Visualization.Display3d_Init(self, handle)
RuntimeError: Aspect_GraphicDeviceDefinitionErrorOpenGl_Window::CreateWindow: glXCreateContext failed. raised from method Init of class Display3d
```

**Comment by ovo-Tim** [comment]
I know that's strange.But when I remove the QMenuWidget,there isn't any problem.
@tpaviot Can you help me?

**Comment by ovo-Tim** [comment]
But,if I InitDriver first,then add QMenuBar,there isn't any problem.
``` python
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from OCC.Core.BRepPrimAPI import BRepPrimAPI_MakeBox
from OCC.Display.OCCViewer import rgb_color
from OCC.Display import OCCViewer

from OCC.Display.backend import load_backend,get_loaded_backend
load_backend("qt-pyside6")
import OCC.Display.qtDisplay as qtDisplay
import sys,os



class MainWindow(QMainWindow):
    BORDER_WIDTH = 5
    def __init__(self):
        super().__init__()

        # self.setWindowFlags(Qt.CustomizeWindowHint)

        self.setGeometry(35, 35, 500, 500)

        self.main_widget = QTabWidget()
        self.setCentralWidget(self.main_widget)

        self.canvas = qtDisplay.qtViewer3d()
        self.canvas.InitDriver()
        self.main_widget.addTab(self.canvas, 'test1')

        self.menu = QMenuBar()
        self.setMenuBar(self.menu)

        self.canvas2 = qtDisplay.qtViewer3d()
        self.canvas2.InitDriver()
        my_box = BRepPrimAPI_MakeBox (10,10,10).Shape()
        self.canvas._display.DisplayShape(my_box,update=True,color=rgb_color(0,1,0))
        self.main_widget.addTab(self.canvas2, 'test2')
        self.main_widget.currentChanged.connect(self.r)

    def r(self):
        self.canvas.InitDriver()
        self.canvas2.InitDriver()

app = QApplication(sys.argv)
win = MainWindow()
win.show()
# win.raise_() 
app.exec_()
```
(Both page 1 and page 2 haven't problem)
