### ISSUE TITLE
Fillet for 2d object

### ISSUE THREAD

**Issue by occstudent** [tpaviot/pythonocc-core#284]
Hello all,
   I am trying to create a fillet for 2d object. But I am stuck at the code.Can any one suggest how to create fillet for a 2d object. The code I tried and the object I want to draw is attached below along with the error I am getting.
**My pythoncode:**
from OCC.gp import gp_Pnt,gp_Dir,gp_Pln,gp_Pnt2d
from OCC.Display.SimpleGui import init_display
from OCC._ChFi2d import ChFi2d_FilletAlgo_Perform,ChFi2d_FilletAlgo_Init,ChFi2d_FilletAPI_Init,ChFi2d_AnaFilletAlgo_Init
from OCC.BRepBuilderAPI import BRepBuilderAPI_MakeEdge,BRepBuilderAPI_MakeWire,BRepBuilderAPI_MakeEdge2d
display,start_display, add_menu,add_functionto_menu = init_display()
p = gp_Pln(gp_Pnt(0,0,0),gp_Dir(0,0,1))
p1 = gp_Pnt2d(0,0) 
p2 = gp_Pnt2d(3,3)
p3 = gp_Pnt2d(-3,3)
ed1 = BRepBuilderAPI_MakeEdge2d(p1,p2).Edge()
ed2 = BRepBuilderAPI_MakeEdge2d(p1,p3).Edge()
f = ChFi2d_AnaFilletAlgo_Init(ed1,ed2,p)
display.DisplayShape(f)
start_display()

**Error Showing:**
runfile('C:/Users/DPTT_GG/Documents/Python Scripts/cylinder.py', wdir='C:/Users/DPTT_GG/Documents/Python Scripts')
Traceback (most recent call last):

  File "<ipython-input-1-effd3985fecf>", line 1, in <module>
    runfile('C:/Users/DPTT_GG/Documents/Python Scripts/cylinder.py', wdir='C:/Users/DPTT_GG/Documents/Python Scripts')
File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/DPTT_GG/Documents/Python Scripts/cylinder.py", line 16, in <module>
    f = ChFi2d_AnaFilletAlgo_Init(ed1,ed2,p)

TypeError: in method 'ChFi2d_AnaFilletAlgo_Init', argument 1 of type 'ChFi2d_AnaFilletAlgo *'

[python code.docx](https://github.com/tpaviot/pythonocc-core/files/339555/python.code.docx)
![capture](https://cloud.githubusercontent.com/assets/20113377/16457437/5d410066-3dd0-11e6-91e4-03450b3bfce0.PNG)

**Comment by occstudent** [comment]
Hello sir,
  Thank you for rectifying my mistakes. Actually I wrote the code in python and I wanted to use BRepBuilderAPI_MakeWire. I can also use directly BRepBuilderMakeWire(ed1,a,ed2).Wire(). Finally thank you for accepting my code as an example.
