### ISSUE TITLE
PySide issue on Windows

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-core#379]
From the Appveyor build:
````
C:\Python27_32\conda-bld\conda_1482921930160\_t_env) C:\Python27_32\conda-bld\conda_1482921930160\work\test>python core_display_pyside_unittest.py 
pyside test
INFO:OCC.Display.backend:backend loaded: qt-pyside
INFO:OCC.Display.SimpleGui:GUI backend set to: qt-pyside
Traceback (most recent call last):
  File "core_display_pyside_unittest.py", line 33, in <module>
    pyside_display, start_display, add_menu, add_function_to_menu = init_display('qt-pyside')
  File "C:\Python27_32\conda-bld\conda_1482921930160\_t_env\lib\site-packages\OCC\Display\SimpleGui.py", line 145, in init_display
    from OCC.Display.qtDisplay import qtViewer3d
  File "C:\Python27_32\conda-bld\conda_1482921930160\_t_env\lib\site-packages\OCC\Display\qtDisplay.py", line 98, in <module>
    class qtViewer3d(qtBaseViewer):
  File "C:\Python27_32\conda-bld\conda_1482921930160\_t_env\lib\site-packages\OCC\Display\qtDisplay.py", line 102, in qtViewer3d
    sig_topods_selected = QtCore.pyqtSignal(list)
AttributeError: 'module' object has no attribute 'pyqtSignal'
(C:\Python27_32\conda-bld\conda_1482921930160\_t_env) C:\Python2
````

**Comment by tpaviot** [comment]
Fixed by commit bff4dffb7017371ba50e1aa35a1fa60c90f84f85
