### ISSUE TITLE
pythonocc 0.18.2: python kernel crashes under macos for invalid parameters

### ISSUE THREAD

**Issue by bernhard-42** [tpaviot/pythonocc-core#655]
I am working with @adam-urbanczyk 's cadquery under macos 10.13.6 and regularly see my python kernel crashing, when I provide by accident parameters that make no sense (build line with x==y, build circle from 3 points that are on a line, create a fillet that is too large for on of the faces, ...).
Happy to get a python exception, since the parameters aren't valid. However python crashing is a bit of a hard punishment for not checking the parameters ;-)

I built a pythonocc environment for pythonocc 0.18.2 (the version which Adam uses) in the following way:

```bash
conda create -n occ python=3.6
conda activate occ
conda install -c pythonocc -c oce -c dlr-sc smesh
conda install -c tpaviot pythonocc-core==0.18.2
```

```python

Result:

Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from OCC.Core.gp import gp_Pnt
>>> from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeEdge
>>> BRepBuilderAPI_MakeEdge(gp_Pnt(0,0,0),gp_Pnt(0,0,0)).Edge()
python(22587,0x7fff957d4380) malloc: *** error for object 0x7fe5e972bb88: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Running under `lldb` shows

```bash
$ lldb
(lldb) file /opt/miniconda/envs/occ/bin/python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/miniconda/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/opt/miniconda/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Current executable set to '/opt/miniconda/envs/occ/bin/python' (x86_64).
(lldb) process launch
Process 23079 launched: '/opt/miniconda/envs/occ/bin/python' (x86_64)
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from OCC.Core.gp import gp_Pnt
>>> from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeEdge
>>> BRepBuilderAPI_MakeEdge(gp_Pnt(0,0,0),gp_Pnt(0,0,0)).Edge()
python(23079,0x7fff957d4380) malloc: *** error for object 0x101b0fed8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Process 23079 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff5d209b66 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff5d209b66 <+10>: jae    0x7fff5d209b70            ; <+20>
    0x7fff5d209b68 <+12>: movq   %rax, %rdi
    0x7fff5d209b6b <+15>: jmp    0x7fff5d200ae9            ; cerror_nocancel
    0x7fff5d209b70 <+20>: retq
Target 0: (python) stopped.
(lldb) thread list
Process 23079 stopped
* thread #1: tid = 0xa05f8, 0x00007fff5d209b66 libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
(lldb) thread backtrace
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff5d209b66 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff5d3d4080 libsystem_pthread.dylib`pthread_kill + 333
    frame #2: 0x00007fff5d1651ae libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff5d2638a6 libsystem_malloc.dylib`free + 521
    frame #4: 0x0000000106889d69 libc++abi.1.dylib`__cxa_end_catch + 137
    frame #5: 0x00000001069b81c1 _BRepBuilderAPI.so`_wrap_BRepBuilderAPI_MakeEdge_Edge(_object*, _object*) + 1313
    frame #6: 0x000000010008a0e2 python`_PyCFunction_FastCallDict + 322
    frame #7: 0x0000000100011171 python`_PyObject_FastCallKeywords + 385
    frame #8: 0x000000010015f718 python`call_function + 392
    frame #9: 0x000000010015d175 python`_PyEval_EvalFrameDefault + 46837
    frame #10: 0x00000001001508c9 python`_PyEval_EvalCodeWithName + 425
    frame #11: 0x00000001001abad3 python`PyRun_InteractiveOneObjectEx + 1123
    frame #12: 0x00000001001a8791 python`PyRun_InteractiveLoopFlags + 433
    frame #13: 0x00000001001a85bb python`PyRun_AnyFileExFlags + 139
    frame #14: 0x00000001001cfb82 python`Py_Main + 4690
    frame #15: 0x0000000100000f59 python`main + 313
    frame #16: 0x00007fff5d0b9015 libdyld.dylib`start + 1
(lldb)
```

A stacktrace for the three point circle axample can be found at https://github.com/CadQuery/cadquery/issues/127#issuecomment-493184502

**Comment by tpaviot** [comment]
It's not the case in pythonocc 7.4.0rc1, I added a test case see commit 33deef2
