### ISSUE TITLE
Tests fails after compiling from sources: libTKHLR not found

### ISSUE THREAD

**Issue by roipoussiere** [tpaviot/pythonocc-core#668]
By following [installation instructions](https://github.com/tpaviot/pythonocc-core/blob/master/INSTALL.md), I installed dependencies, cloned the repo and compiled sources without having any warning.

But when run `python run_tests.py`, I get the following error:

```
Traceback (most recent call last):
  File "run_tests.py", line 22, in <module>
    import core_wrapper_features_unittest
  File "/home/nath/divers/pythonocc-core/test/core_wrapper_features_unittest.py", line 27, in <module>
    from OCC.Core.Standard import Standard_Transient, Handle_Standard_Transient
  File "/usr/lib/python3.7/site-packages/OCC/Core/Standard.py", line 25, in <module>
    from . import _Standard
ImportError: libTKHLR.so.11: cannot open shared object file: No such file or directory
```

I use Manjaro Linux 18.0.4

**Comment by roipoussiere** [comment]
`sudo find / -name "libTKHLR.so.11" ` gave me `/usr/local/lib/libTKHLR.so.11`, so I try compiling again by giving this directory to cmake:

```
cmake -DOCE_INCLUDE_PATH=/usr/local/include/oce -DOCE_LIB_PATH=/usr/local/lib/ ..
```

**Comment by roipoussiere** [comment]
Ok I got it.

As suggested in #627, I added `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/` in my .zshrc, then sourced it, then the error disappeared.

Maybe the documentation for compiling from sources could be improved to avoid similar issues:
- make it clear that when compiling oce from sources, the default oce lib path is `/usr/local/lib/` so we have to specify this folder when running cmake;
- explain that we have to add this `export LD_LIBRARY_PATH` line in the .bashrc / .zshrc / .whateverrc
