### ISSUE TITLE
conda install problem

### ISSUE THREAD

**Issue by beskep** [tpaviot/pythonocc-core#669]
I updated packages yesterday, and my environment have used for months is broken.

Whenever try to load pythonocc-core, this error occures.
(not only OCC.Core.gp)

```
C:\Miniconda3\envs\bim\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 57781 --file E:/Python/IFCConverter/IFCConverter/converter/ifc_converter.py
pydev debugger: process 10060 is connecting

Connected to pydev debugger (build 192.5728.105)
C:\Miniconda3\envs\bim\lib\site-packages\OCC\BRepTools.py:3: DeprecationWarning: OCC.BRepTools is deprecated since pythonocc-0.18.2. Use OCC.Core.BRepTools
  warnings.warn("OCC.BRepTools is deprecated since pythonocc-0.18.2. Use OCC.Core.BRepTools", DeprecationWarning)
Traceback (most recent call last):
  File "C:\Miniconda3\envs\bim\lib\site-packages\OCC\Core\BRepExtrema.py", line 25, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Miniconda3\envs\bim\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: 지정된 프로시저를 찾을 수 없습니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 2060, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/Python/IFCConverter/IFCConverter/converter/ifc_converter.py", line 13, in <module>
    from OCC.Core.BRepExtrema import BRepExtrema_DistShapeShape
  File "C:\Miniconda3\envs\bim\lib\site-packages\OCC\Core\BRepExtrema.py", line 28, in <module>
    _BRepExtrema = swig_import_helper()
  File "C:\Miniconda3\envs\bim\lib\site-packages\OCC\Core\BRepExtrema.py", line 27, in swig_import_helper
    return importlib.import_module('_BRepExtrema')
  File "C:\Miniconda3\envs\bim\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_BRepExtrema'

Process finished with exit code 1
```

'지정된 프로시저를 찾을 수 없습니다' means 'The specified procedure could not be found'

The revision is:
```
2019-08-05 11:07:30  (rev 11)
     atomicwrites  {1.3.0 -> 1.3.0 (conda-forge)}
     attrs  {19.1.0 -> 19.1.0 (conda-forge)}
     ca-certificates  {2019.5.15 -> 2019.6.16 (conda-forge)}
     certifi  {2019.6.16 -> 2019.6.16 (conda-forge)}
     colorama  {0.4.1 -> 0.4.1 (conda-forge)}
     cycler  {0.10.0 -> 0.10.0 (conda-forge)}
     freetype  {2.9.1 -> 2.10.0 (conda-forge)}
     icu  {58.2 -> 64.2 (conda-forge)}
     ifcopenshell  {0.6.0a1 (ifcopenshell) -> v0.6.0b0 (conda-forge)}
     importlib_metadata  {0.17 -> 0.18 (conda-forge)}
     jpeg  {9b -> 9c (conda-forge)}
     kiwisolver  {1.1.0 -> 1.1.0 (conda-forge)}
     libpng  {1.6.37 -> 1.6.37 (conda-forge)}
     matplotlib  {3.1.0 -> 3.1.1 (conda-forge)}
     more-itertools  {7.0.0 -> 7.2.0 (conda-forge)}
     numpy  {1.16.4 -> 1.17.0 (conda-forge)}
     openssl  {1.1.1c -> 1.1.1c (conda-forge)}
     packaging  {19.0 -> 19.0 (conda-forge)}
     pandas  {0.25.0 -> 0.25.0 (conda-forge)}
     pip  {19.1.1 -> 19.2.1 (conda-forge)}
     pluggy  {0.12.0 -> 0.12.0 (conda-forge)}
     progressbar2  {3.37.1 -> 3.41.0 (conda-forge)}
     py  {1.8.0 -> 1.8.0 (conda-forge)}
     pyparsing  {2.4.0 -> 2.4.2 (conda-forge)}
     pyqt  {5.9.2 -> 5.9.2 (conda-forge)}
     pytest  {4.6.2 -> 5.0.1 (conda-forge)}
     pytest-runner  {4.4 -> 5.1 (conda-forge)}
     python  {3.6.8 -> 3.6.7 (conda-forge)}
     python-dateutil  {2.8.0 -> 2.8.0 (conda-forge)}
     python-utils  {2.3.0 -> 2.3.0 (conda-forge)}
     pythonocc-core  {0.18.2 (tpaviot) -> 0.18.2 (CadQuery)}
     pytz  {2019.1 -> 2019.2 (conda-forge)}
     qt  {5.9.7 -> 5.9.7 (conda-forge)}
     scipy  {1.2.1 -> 1.3.0}
     setuptools  {41.0.1 -> 41.0.1 (conda-forge)}
     sip  {4.19.8 -> 4.19.8 (conda-forge)}
     six  {1.12.0 -> 1.12.0 (conda-forge)}
     sqlite  {3.28.0 -> 3.29.0 (conda-forge)}
     tbb  {2019.4 -> 2019.7 (conda-forge)}
     tornado  {6.0.2 -> 6.0.3 (conda-forge)}
     wcwidth  {0.1.7 -> 0.1.7 (conda-forge)}
     wheel  {0.33.4 -> 0.33.4 (conda-forge)}
     wincertstore  {0.2 -> 0.2 (conda-forge)}
     wxpython  {4.0.4 -> 4.0.6 (conda-forge)}
     zipp  {0.5.1 -> 0.5.2 (conda-forge)}
     zlib  {1.2.11 -> 1.2.11 (conda-forge)}
    -libboost-1.67.0
    -mkl_fft-1.0.12
    -mkl_random-1.0.2
    -numpy-base-1.16.4
    -smesh-6.7.6 (pythonocc)
    -xz-5.2.4
    +asn1crypto-0.24.0 (conda-forge)
    +boost-cpp-1.70.0 (conda-forge)
    +cffi-1.12.3 (conda-forge)
    +chardet-3.0.4 (conda-forge)
    +cryptography-2.7 (conda-forge)
    +idna-2.8 (conda-forge)
    +libblas-3.8.0 (conda-forge)
    +libcblas-3.8.0 (conda-forge)
    +libiconv-1.15 (conda-forge)
    +liblapack-3.8.0 (conda-forge)
    +libxml2-2.9.9 (conda-forge)
    +m2w64-gcc-libgfortran-5.3.0
    +m2w64-gcc-libs-5.3.0
    +m2w64-gcc-libs-core-5.3.0
    +m2w64-gmp-6.1.0
    +m2w64-libwinpthread-git-5.0.0.4634.697f757
    +matplotlib-base-3.1.1 (conda-forge)
    +mkl-service-2.1.0 (conda-forge)
    +msys2-conda-epoch-20160418
    +occt-7.3.0 (conda-forge)
    +pathlib2-2.3.4 (conda-forge)
    +pthread-stubs-0.4 (conda-forge)
    +pycparser-2.19 (conda-forge)
    +pyopenssl-19.0.0 (conda-forge)
    +pypubsub-4.0.3 (conda-forge)
    +pysocks-1.7.0 (conda-forge)
    +requests-2.22.0 (conda-forge)
    +urllib3-1.25.3 (conda-forge)
    +win_inet_pton-1.1.0 (conda-forge)
```

And my current environment is:

```
# Name                    Version                   Build  Channel
atomicwrites              1.3.0                    py36_1
attrs                     19.1.0                   py36_1
blas                      1.0                         mkl
ca-certificates           2019.5.15                     0
certifi                   2019.6.16                py36_1
colorama                  0.4.1                    py36_0
cycler                    0.10.0           py36h009560c_0
freeimageplus             3.17.0                        0    CadQuery
freetype                  2.9.1                ha9979f8_1
gl2ps                     1.3.8                hfa6e2cd_4    dlr-sc
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
ifcopenshell              0.6.0a1             py36_vc14_0  [vc14]  ifcopenshell
importlib_metadata        0.17                     py36_1
intel-openmp              2019.4                      245
jpeg                      9b                   hb83a4c4_2
kiwisolver                1.1.0            py36ha925a31_0
libboost                  1.67.0               hd9e427e_4
libpng                    1.6.37               h2a8f88b_0
matplotlib                3.1.0            py36hc8f65d3_0
mkl                       2019.4                      245
mkl_fft                   1.0.12           py36h14836fe_0
mkl_random                1.0.2            py36h343c172_0
more-itertools            7.0.0                    py36_0
numpy                     1.16.4           py36h19fb1c0_0
numpy-base                1.16.4           py36hc3f5095_0
oce                       0.18.3                   vc14_3  [vc14]  oce
openssl                   1.1.1c               he774522_1
packaging                 19.0                     py36_0
pandas                    0.25.0           py36ha925a31_0
pip                       19.1.1                   py36_0
pluggy                    0.12.0                     py_0
progressbar2              3.37.1                   py36_0
py                        1.8.0                    py36_0
pyparsing                 2.4.0                      py_0
pyqt                      5.9.2            py36h6538335_2
pytest                    4.6.2                    py36_0
pytest-runner             4.4                        py_0
python                    3.6.8                h9f7ef89_7
python-dateutil           2.8.0                    py36_0
python-utils              2.3.0                    py36_0
pythonocc-core            0.18.2          py36_vc14h24bf2e0_281  [vc14]  tpaviot
pytz                      2019.1                     py_0
qt                        5.9.7            vc14h73c81de_0
scipy                     1.2.1            py36h29ff71c_0
setuptools                41.0.1                   py36_0
sip                       4.19.8           py36h6538335_0
six                       1.12.0                   py36_0
smesh                     6.7.6                    vc14_7  [vc14]  pythonocc
sqlite                    3.28.0               he774522_0
tbb                       2019.4               h74a9793_0
tornado                   6.0.2            py36he774522_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7            py36h3d5aa90_0
wheel                     0.33.4                   py36_0
wincertstore              0.2              py36h7fe50ca_0
wxpython                  4.0.4            py36ha925a31_0
xz                        5.2.4                h2fa13f4_4
zipp                      0.5.1                      py_0
zlib                      1.2.11               h62dcd97_3
```

I tried rollback and changed channel to 'tpaviot', it did not work.
Is this possibly other packages' problem?

Thank you for reading.

**Comment by beskep** [comment]
Problem solved
though I can't understand why...

```
# packages in environment at C:\Miniconda3\envs\bim:
#
# Name                    Version                   Build  Channel
atomicwrites              1.3.0                    py36_1
attrs                     19.1.0                   py36_1
blas                      1.0                         mkl
certifi                   2019.6.16                py36_1
colorama                  0.4.1                    py36_0
freeimageplus             3.17.0                        0    cadquery
freetype                  2.9.1                ha9979f8_1
gl2ps                     1.3.8                hfa6e2cd_4    dlr-sc
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
ifcopenshell              0.6.0a1             py36_vc14_0  [vc14]  ifcopenshell
importlib_metadata        0.19                     py36_0
intel-openmp              2019.4                      245
libboost                  1.67.0               hd9e427e_4
libpng                    1.6.37               h2a8f88b_0
mkl                       2019.4                      245
mkl-service               2.0.2            py36he774522_0
mkl_fft                   1.0.12           py36h14836fe_0
mkl_random                1.0.2            py36h343c172_0
more-itertools            7.2.0                    py36_0
numpy                     1.16.4           py36h19fb1c0_0
numpy-base                1.16.4           py36hc3f5095_0
oce                       0.18.3                   vc14_3  [vc14]  oce
packaging                 19.0                     py36_0
pandas                    0.25.0           py36ha925a31_0
pip                       19.1.1                   py36_0
pluggy                    0.12.0                     py_0
progressbar2              3.37.1                   py36_0
py                        1.8.0                    py36_0
pyparsing                 2.4.0                      py_0
pytest                    5.0.1                    py36_0
pytest-runner             5.1                        py_0
python                    3.6.9                h5500b2f_0
python-dateutil           2.8.0                    py36_0
python-utils              2.3.0                    py36_0
pythonocc-core            0.18.2          py36_vc14h24bf2e0_281  [vc14]  tpaviot
pytz                      2019.1                     py_0
scipy                     1.3.0            py36h29ff71c_0
setuptools                41.0.1                   py36_0
six                       1.12.0                   py36_0
smesh                     6.7.6                    vc14_7  [vc14]  pythonocc
sqlite                    3.29.0               he774522_0
tbb                       2019.4               h74a9793_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7            py36h3d5aa90_0
wheel                     0.33.4                   py36_0
wincertstore              0.2              py36h7fe50ca_0
xz                        5.2.4                h2fa13f4_4
zipp                      0.5.2                      py_0
zlib                      1.2.11               h62dcd97_3
```
