### ISSUE TITLE
AIS_InteractiveContext::ShiftSelect , I'm not sure if this is a bug?

### ISSUE THREAD

**Issue by mahaidong** [tpaviot/pythonocc-core#726]
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/pythonocc/lib/python3.7/site-packages/OCC/Display/qtDisplay.py", line 229, in mouseReleaseEvent
    self._display.ShiftSelect(pt.x(), pt.y())
  File "/usr/local/miniconda3/envs/pythonocc/lib/python3.7/site-packages/OCC/Display/OCCViewer.py", line 633, in ShiftSelect
    self.Context.ShiftSelect()
TypeError: Wrong number or type of arguments for overloaded function 'AIS_InteractiveContext_ShiftSelect'.
  Possible C/C++ prototypes are:
    AIS_InteractiveContext::ShiftSelect(Standard_Boolean const)
    AIS_InteractiveContext::ShiftSelect(TColgp_Array1OfPnt2d const &,opencascade::handle< V3d_View > const &,Standard_Boolean const)
    AIS_InteractiveContext::ShiftSelect(Standard_Integer const,Standard_Integer const,Standard_Integer const,Standard_Integer const,opencascade::handle< V3d_View > const &,Standard_Boolean const)
Abort trap: 6

**Comment by tpaviot** [comment]
@mahaidong Thank you for your fix
