### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by khyatiip** [tpaviot/pythonocc-core#772]
Hello,

When i run my python script using Spyder, no error is raised. It works perfectly fine. But when I run the same python script using a batch script, I get the following error. How do I solve this?
```
C:\Users\KHYATI\Desktop\Thesis>python "C:\Users\KHYATI\Desktop\Thesis\_FenestrationSurface.py"
Traceback (most recent call last):
  File "C:\Users\KHYATI\Desktop\Thesis\_FenestrationSurface.py", line 3, in <module>
    from OCC.Core import TopoDS
  File "C:\Users\KHYATI\AppData\Local\Programs\Python\Python37\lib\site-packages\OCC\Core\TopoDS.py", line 18, in <module>
    from . import _TopoDS
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by qunat** [comment]
can you show your code?

**Comment by tpaviot** [comment]
I guess there's something wrong with your PATH or PYTHONPATH

**Comment by tpaviot** [comment]
solved ?

**Comment by lanix516** [comment]
Hello,
    have you solved this?

**Comment by tpaviot** [comment]
no

**Comment by lanix516** [comment]
change python 3.8
conda install -c tpaviot  pythonocc-core=7.4.0
It works very well。
