### ISSUE TITLE
Again: SetPixelFormat failed. Error code: 2000 raised from method Init of class Display3d

### ISSUE THREAD

**Issue by thomasTUK** [tpaviot/pythonocc-core#999]
Hello. I have just done the same as zapoye and what @tpaviot recommended.

```
K:\Daten\GitLab\pythonocc-demos\examples>python core_helloworld.py
qt-pyqt5 backend - Qt version 5.9.7
####### 3D rendering pipe initialisation #####
Display3d class initialization starting ...
Aspect_DisplayConnection created.
OpenGl_GraphicDriver created.
V3d_Viewer created.
AIS_InteractiveContext created.
V3d_View created
WNT window created.
Traceback (most recent call last):
  File "K:\Daten\GitLab\pythonocc-demos\examples\core_helloworld.py", line 38, in <module>
    display, start_display, add_menu, add_function_to_menu = init_display()
  File "K:\Programme\Anaconda3\envs\ifcopenshell\lib\site-packages\OCC\Display\SimpleGui.py", line 198, in init_display
    win.canva.InitDriver()
  File "K:\Programme\Anaconda3\envs\ifcopenshell\lib\site-packages\OCC\Display\qtDisplay.py", line 102, in InitDriver
    self._display.Create(window_handle=int(self.winId()), parent=self)
  File "K:\Programme\Anaconda3\envs\ifcopenshell\lib\site-packages\OCC\Display\OCCViewer.py", line 176, in Create
    self.Init(self._window_handle)
  File "K:\Programme\Anaconda3\envs\ifcopenshell\lib\site-packages\OCC\Core\Visualization.py", line 171, in Init
    return _Visualization.Display3d_Init(self, handle)
RuntimeError: Aspect_GraphicDeviceDefinitionErrorOpenGl_Window::CreateWindow: SetPixelFormat failed. Error code: 2000 raised from method Init of class Display3d
```

I change 

`class qtBaseViewer(QtOpenGL.QGLWidget):`

to

`class qtBaseViewer(QtWidgets.QWidget):`

![grafik](https://user-images.githubusercontent.com/79101120/117537215-d92c1c00-afff-11eb-8327-3a6036a7aa53.png)

Unfortunetely, I get now a different error:

`K:\Daten\GitLab\pythonocc-demos\examples>python core_helloworld.py
Traceback (most recent call last):
  File "K:\Daten\GitLab\pythonocc-demos\examples\core_helloworld.py", line 38, in <module>
    display, start_display, add_menu, add_function_to_menu = init_display()
  File "K:\Programme\Anaconda3\envs\ifcopenshell\lib\site-packages\OCC\Display\SimpleGui.py", line 134, in init_display
    from OCC.Display.qtDisplay import qtViewer3d
  File "K:\Programme\Anaconda3\envs\ifcopenshell\lib\site-packages\OCC\Display\qtDisplay.py", line 38, in <module>
    class qtBaseViewer(QGLWidget.QtOpenGL):
NameError: name 'QGLWidget' is not defined`

Did i do something wrong?

**Comment by tpaviot** [comment]
The correct syntax is ``  class qtBaseViewer(QtWidgets.QWidget):`` see  https://github.com/tpaviot/pythonocc-core/commit/a028f6063fb1f2506d7ab42802f565c74019d1e7
